const makeItem = (id, options) => ({ id, ...options });

export const HELP_OVERLAY_ITEMS = [
  makeItem("canvas-left", {
    group: "canvas",
    action: "Tap left",
    body: "previous item in history.",
    labelPlacement: "absolute",
    absolute: { x: 0.34, y: 0.22 },
    targetPoint: { x: 0.24, y: 0.52 },
  }),
  makeItem("canvas-right", {
    group: "canvas",
    action: "Tap right",
    body: "next item in history or random next, depending on mode.",
    labelPlacement: "absolute",
    absolute: { x: 0.56, y: 0.22 },
    targetPoint: { x: 0.76, y: 0.52 },
  }),
  makeItem("slider-drag", {
    group: "slider",
    action: "Drag slider",
    body: "change assigned parameter value.",
    targetSelector: "#quickSlider",
    labelPlacement: "absolute",
    absolute: { x: 0.50, y: 0.72 },
  }),
  makeItem("slider-double-tap", {
    group: "slider",
    action: "Double-tap header",
    body: "set a, b, c or d to zero.",
    targetSelector: "#quickSlider .qsTop",
    labelPlacement: "absolute",
    absolute: { x: 0.18, y: 0.72 },
  }),
  makeItem("slider-plus-minus", {
    group: "slider",
    action: "Tap − or +",
    body: "fine control.",
    targetSelector: "#quickSlider .qsControlRow",
    labelPlacement: "absolute",
    absolute: { x: 0.88, y: 0.76 },
  }),
  makeItem("formula-cmap-tap", {
    group: "bottomTiles",
    action: "Tap tile",
    body: "open selection list and adjust settings.",
    targetSelector: "#formulaBtn",
    labelPlacement: "absolute",
    absolute: { x: 0.12, y: 0.76 },
  }),
  makeItem("formula-cmap-double", {
    group: "bottomTiles",
    action: "Double-tap tile",
    body: "toggle fixed or random.",
    targetSelector: "#cmapBtn",
    labelPlacement: "absolute",
    absolute: { x: 0.21, y: 0.80 },
  }),
  makeItem("params-tap", {
    group: "params",
    action: "Tap tile",
    body: "assign to slider control.",
    targetSelector: "#btnAlpha",
    labelPlacement: "absolute",
    absolute: { x: 0.34, y: 0.76 },
  }),
  makeItem("params-double", {
    group: "params",
    action: "Double-tap tile",
    body: "toggle fixed or random.",
    targetSelector: "#btnBeta",
    labelPlacement: "absolute",
    absolute: { x: 0.46, y: 0.80 },
  }),
  makeItem("params-swipe-v", {
    group: "params",
    action: "Swipe up or down",
    body: "assign vertical screen control.",
    targetSelector: "#btnDelta",
    labelPlacement: "absolute",
    absolute: { x: 0.58, y: 0.76 },
  }),
  makeItem("params-swipe-h", {
    group: "params",
    action: "Swipe left or right",
    body: "assign horizontal screen control.",
    targetSelector: "#btnGamma",
    labelPlacement: "absolute",
    absolute: { x: 0.68, y: 0.80 },
  }),
  makeItem("params-long", {
    group: "params",
    action: "Long press",
    body: "clear screen control assignment.",
    targetSelector: "#btnAlpha",
    labelPlacement: "absolute",
    absolute: { x: 0.12, y: 0.84 },
  }),
  makeItem("iter-tap", {
    group: "iter",
    action: "Tap tile",
    body: "assign to slider control.",
    targetSelector: "#btnIters",
    labelPlacement: "absolute",
    absolute: { x: 0.82, y: 0.76 },
  }),
  makeItem("iter-double", {
    group: "iter",
    action: "Double-tap tile",
    body: "toggle fixed or random.",
    targetSelector: "#btnIters",
    labelPlacement: "absolute",
    absolute: { x: 0.70, y: 0.84 },
  }),
  makeItem("random-all", {
    group: "random",
    action: "Double-tap this tile",
    body: "toggles all tiles to random or fixed.",
    targetSelector: "#randomModeBtn",
    labelPlacement: "absolute",
    absolute: { x: 0.92, y: 0.80 },
  }),
  makeItem("top-view", {
    group: "topbar",
    action: "View",
    body: "show Lyapunov overlay in screen control mode.",
    targetSelector: "#overlayToggleBtn",
    labelPlacement: "absolute",
    absolute: { x: 0.84, y: 0.16 },
  }),
  makeItem("top-help", {
    group: "topbar",
    action: "Help",
    body: "open or close this help.",
    targetSelector: "#helpBtn",
    labelPlacement: "absolute",
    absolute: { x: 0.84, y: 0.20 },
  }),
  makeItem("top-settings", {
    group: "topbar",
    action: "Settings",
    body: "open or close app settings.",
    targetSelector: "#rangesEditorToggle",
    labelPlacement: "absolute",
    absolute: { x: 0.84, y: 0.24 },
  }),
  makeItem("top-scale", {
    group: "topbar",
    action: "Auto Scale",
    body: "fit content to screen automatically.",
    targetSelector: "#scaleModeBtn",
    labelPlacement: "absolute",
    absolute: { x: 0.84, y: 0.28 },
  }),
  makeItem("top-camera", {
    group: "topbar",
    action: "Camera",
    body: "save image.",
    targetSelector: "#cameraBtn",
    labelPlacement: "absolute",
    absolute: { x: 0.84, y: 0.32 },
  }),
];

export const HELP_GROUP_BRACKETS = [
  {
    id: "formula-cmap-group",
    targetSelectors: ["#formulaBtn", "#cmapBtn"],
    position: "top",
  },
  {
    id: "params-group",
    targetSelectors: ["#btnAlpha", "#btnBeta", "#btnDelta", "#btnGamma"],
    position: "top",
  },
];
